# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

parameters:

  - name: pipelinesWords
    type: object  
    default:
    - WillCreate
    - CreateApk
    - pipeline3

trigger:
- "*"

pool:
  vmImage: 'macOS-10.15'

stages:

- stage: Check_Commit_Message
  condition: ${{ containsValue(parameters.pipelinesWords, variables['Build.SourceVersionMessage']) }}
  jobs:
  - job: B1
    steps:
      - script: echo Commit is valid!