# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

parameters:

  - name: pipelinesWords
    type: object  
    default:
    - WillCreate
    - CreateApk
    - pipeline3

trigger:
- "*"

pool:
  vmImage: 'macOS-10.15'

stages:

- stage: Check_Commit_Message
  condition: ${{ containsValue(parameters.pipelinesWords, variables['Build.SourceVersionMessage']) }}
  jobs:
  - job: Job1
    steps:
      - script: echo Commit is valid!




- stage: BuildApp    
  dependsOn: Check_Commit_Message
  jobs:
  - job: Job2
    steps:
      - script: echo Start building! 
      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          publishJUnitResults: false
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'assembleProd1'


